# Generated by Django 5.0.3 on 2024-03-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='description',
            field=models.TextField(default='описание хакатона'),
        ),
    ]
