# Generated by Django 4.2.2 on 2024-03-31 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackathons', '0002_hackathon_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='max_participants',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='min_participants',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='participans',
            field=models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
