# Generated by Django 4.2.2 on 2024-03-31 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackathons', '0003_hackathon_max_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='participans',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='participants',
            field=models.ManyToManyField(null=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='image_cover',
            field=models.ImageField(null=True, upload_to='hackathon_images/'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='max_participants',
            field=models.IntegerField(default=5, null=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='min_participants',
            field=models.IntegerField(default=3, null=True),
        ),
    ]
