# Generated by Django 4.2.6 on 2024-03-31 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_organizator',
            field=models.BooleanField(),
        ),
    ]
