# Generated by Django 4.2.6 on 2024-03-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_cover', models.ImageField(upload_to='project_images/')),
                ('description', models.TextField()),
            ],
        ),
    ]
