# Generated by Django 5.0.3 on 2024-03-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hackathons', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('age', models.IntegerField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('work_exp', models.IntegerField(blank=True)),
                ('role', models.CharField(max_length=100)),
                ('hackathons', models.ManyToManyField(to='hackathons.hackathon')),
                ('teams', models.ManyToManyField(to='projects.project')),
            ],
        ),
    ]
